#ifndef HEAD_H
#define HEAD_H
#include "RooAbsData.h"
#include "RooAbsMoment.h"
#include "RooAbsPdf.h"
#include "RooAbsReal.h"
#include "RooArgSet.h"
#include "RooBifurGauss.h"
#include "RooBreitWigner.h"
#include "RooCategory.h"
#include "RooCBShape.h"
#include "RooChebychev.h"
#include "RooChi2Var.h"
#include "RooConstVar.h"
#include "RooDataHist.h"
#include "RooDataSet.h"
#include "RooFitResult.h"
#include "RooFormulaVar.h"
#include "RooGaussian.h"
#include "RooGenericPdf.h"
#include "RooGlobalFunc.h"
#include "RooHist.h"
#include "RooHistPdf.h"
#include "RooKeysPdf.h"
#include "RooLandau.h"
#include "RooMinimizer.h"
#include "RooMinuit.h"
#include "RooNDKeysPdf.h"
#include "RooNLLVar.h"
#include "RooPlot.h"
#include "RooPoisson.h"
#include "RooPolynomial.h"
#include "RooPrintable.h"
#include "RooProdPdf.h"
#include "RooProfileLL.h"
#include "RooRealVar.h"
#include "RooSimultaneous.h"
#include "RooUniform.h"
#include "RooVoigtian.h"
#include "RooWorkspace.h"
#include "TCanvas.h"
#include "TF1.h"
#include "TFile.h"
#include "TGaxis.h"
#include "TGaxis.h"
#include "TH2.h"
#include "TLatex.h"
#include "TLegend.h"
#include "TLegendEntry.h"
#include "TROOT.h"  
#include "TString.h"
#include "TSystem.h"
#include "TTree.h"
#include <RooAddPdf.h>
#include <RooArgList.h>
#include <RooExponential.h>
#include <RooFitResult.h>
#include <RooFormula.h>
#include <RooFormulaVar.h>
#include <RooPolyVar.h>

#endif

